services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: idems/stack-api-example:latest
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./js:/usr/share/nginx/html/js
      - ./questions:/usr/share/nginx/html/questions
  maxima:
    image: mathinstitut/goemaxima:2024072400-latest
    tmpfs:
      - "/tmp"
    restart: unless-stopped
    cap_add:
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    environment:
      GOEMAXIMA_QUEUE_LEN: 32
    read_only: true
  stack:
    image: idems/stackapi:latest
    build: ./stackapi
    restart: unless-stopped
    ports:
      - "3080:80"
